services:
  frontend:
    container_name: frontend
    image: frontend
    build:
      context: .
    ports:
      - '3000:3000'
    networks:
      - app
    env_file:
      - .env
  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./etc/nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
    networks:
      - app

networks:
  app:
